spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    first:
      jdbc-url: jdbc:postgresql://localhost:5433/db1
      username: doniy
      password: doniy
    second:
      jdbc-url: jdbc:postgresql://localhost:5432/db1
      username: doniy
      password: doniy


#  jpa:
#    show-sql: off
#    hibernate:
#      ddl-auto: update
#    generate-ddl: on
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        enable_lazy_load_no_trans: true
#        generate_statistics: false
#        jdbc:
#          lob:
#            non_contextual_creation: true
